# Generated by Django 4.1 on 2023-01-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_rep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_wholesaler',
        ),
    ]
