# Generated by Django 4.1 on 2023-01-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_rep_remove_user_is_wholesaler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=24),
        ),
    ]
