# Generated by Django 4.1 on 2023-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_city_region_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_id',
            field=models.IntegerField(),
        ),
    ]
