# Generated by Django 4.1 on 2023-01-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_city_region_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_rep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_wholesaler',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='rep_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.rep'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.seller'),
        ),
        migrations.AddField(
            model_name='user',
            name='wholesaler_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.wholesaler'),
        ),
    ]
