# Generated by Django 4.1 on 2023-01-27 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='allowed_seller_numbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('is_available', models.BooleanField(default=False)),
                ('seller_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.seller')),
            ],
        ),
    ]
