# Generated by Django 4.1 on 2023-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_allowed_seller_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_seller_numbers',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
