# Generated by Django 4.1 on 2023-01-27 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_allowed_seller_numbers_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowed_seller_numbers',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='allowed_seller_numbers',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
