# Generated by Django 4.1 on 2023-01-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_allowed_seller_numbers_seller_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesaler',
            old_name='products_descriptoin',
            new_name='descriptoin',
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='business_name',
            field=models.CharField(default='business', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='products_types',
            field=models.TextField(),
        ),
    ]
