# Generated by Django 4.1 on 2023-01-29 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_products_descriptoin_wholesaler_descriptoin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='rep',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/upload/rep_photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='store_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/upload/store_photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
