# Generated by Django 4.1 on 2023-02-03 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_photo_rep_photo_wholesaler_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/upload/reps_photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='يمكن رفع الصور فقط بالصيغات التالية: (jpg, png, jpeg)')]),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='store_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/upload/wholesalers_stores_photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='يمكن رفع الصور فقط بالصيغات التالية: (jpg, png, jpeg)')]),
        ),
    ]
