# Generated by Django 4.1 on 2023-02-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_rep_photo_alter_wholesaler_store_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesaler',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
