# Generated by Django 4.1 on 2023-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_likes'),
        ('users', '0019_rename_descriptoin_wholesaler_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_stores',
            field=models.ManyToManyField(blank=True, related_name='+', to='stores.store'),
        ),
    ]
