# Generated by Django 4.1 on 2023-02-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rep_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.rep'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wholesaler_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.wholesaler'),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.city'),
        ),
    ]
