# Generated by Django 4.1 on 2023-03-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_rep_city_alter_user_rep_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allowed_seller_numbers',
        ),
    ]
