# Generated by Django 4.1 on 2023-02-03 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='static/upload/sellers_stores_photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'], message='يمكن رفع الصور فقط بالصيغات التالية: (jpg, png, jpeg)')]),
        ),
    ]
