# Generated by Django 4.1 on 2023-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_category_store_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
